#!/usr/bin/env php
<?php

use Tempest\Framework\Tempest;

try {
    require_once __DIR__ . '/vendor/autoload.php';
} catch (Throwable) {
    require_once getcwd() . '/../autoload.php';
}

Tempest::boot(__DIR__)->console()->run();

exit;